kotlin.code.style=official

android.useAndroidX=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
kotlin.daemon.jvmargs=-Xmx4096m
kotlin.native.ignoreDisabledTargets=true

# Performance & Build Speed Optimizations
org.gradle.caching=true
org.gradle.parallel=true
kotlin.incremental=true
kotlin.incremental.native=true
